version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
