import type { Metadata } from "next";
import TopMenu from "../../../components/layout/topMenu/TopMenu";
import Footer from "../../../components/layout/footer/Footer";

const title = 'Intra'

export const metadata: Metadata = {
    title,
    description: "Generated by create next app",
    icons: {
        //icon: '/favicon.ico',
    },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
          <TopMenu title={title} />
          <main>{children}</main>
          <Footer/>
      </div>
  );
}
