import type { Metadata } from "next";
import TopMenu from "@intra/ui/components/layout/topMenu/TopMenu";
import Footer from "@intra/ui/components/layout/footer/Footer";

/**
 * Oldal címe
 */
const title = 'Intra'

/**
 * Meta aadatok
 */
export const metadata: Metadata = {
    title,
    description: "Generated by create next app",
    icons: {
        //icon: '/favicon.ico',
    },
};

/**
 * Publikus útvonalak layoutja
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div>
          {/*Top menü*/}
          <TopMenu title={title} />

          {/*Main content*/}
          <main>{children}</main>

          {/*Footer*/}
          <Footer/>
      </div>
  );
}
