import TopMenu from "@intra/ui/components/layout/topMenu/TopMenu";
import Footer from "@intra/ui/components/layout/footer/Footer";
import SideMenu from "@intra/ui/components/layout/SideMenu/SideMenu";
import {getLocale} from "next-intl/server";
import {auth} from "../../../auth";

/**
 * Oldal címe
 */
const title = 'Intra'

// /**
//  * Meta aadatok
//  */
// export const metadata: Metadata = {
//     title,
//     description: "Generated by create next app",
//     icons: {
//         //icon: '/favicon.ico',
//     },
// };

/**
 * Privát útvonalak layoutja
 */
export default async function PrivateLayout({
                                                children,
                                            }: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale()
    const session = await auth()

    console.log('session', session)

    const menuItems = [
        { name: 'Főoldal', href: `${locale}/private/home` },
        { name: 'Felhasználók', href: `${locale}/admin/users` },
    ]

    return (
        <div>
            {/*Top menü*/}
            <TopMenu title={title} />

            <div className="flex mt-[53px]">
                {/*Baloldali menü*/}
                <div className="w-1/5">
                    <SideMenu
                        menuItems={menuItems}
                    />
                </div>

                {/*Main content*/}
                <div className="w-4/5">
                    <main>{children}</main>
                </div>
            </div>

            {/*Footer*/}
            <Footer/>
        </div>
    );
}
